#!/usr/bin/env node
/*
 * Browser smoke for the full pages generated by generate_page.py: the 12 page
 * types with their defaults, plus the options that change the page structure
 * (--no-header, --no-footer, --dark, --brand-mode republique).
 * Returns SKIPPED with exit code 2 when Playwright, Chromium, Python, or the
 * cached DSFR package is unavailable. A failure observed before a skip is
 * never lost: FAIL wins over SKIPPED.
 */

const fs = require('fs');
const os = require('os');
const path = require('path');
const {
  cleanup,
  loadPlaywright,
  patchDsfrCdnToLocal,
  printSkipped,
  resolveDsfrPackage,
  runPython,
  startStaticServer,
  waitForDsfr,
} = require('./playwright_dsfr_helpers');

const SKILL_DIR = path.resolve(__dirname, '..');
const PAGE_SCRIPT = path.join(SKILL_DIR, 'scripts', 'generate_page.py');
const FOCUSABLE_TAGS = ['A', 'BUTTON', 'INPUT', 'SELECT', 'TEXTAREA'];

// La liste des types vient du générateur : un type ajouté est couvert d'office.
function readPageTypes() {
  const code = 'import json, sys; sys.path.insert(0, sys.argv[1]); import generate_page; print(json.dumps(generate_page.PAGE_TYPES))';
  const result = runPython(['-c', code, __dirname], { cwd: SKILL_DIR });
  if (!result.ok) return result;
  const types = JSON.parse(result.stdout);
  if (!Array.isArray(types) || types.length === 0) return { ok: false, skip: false, error: 'PAGE_TYPES vide ou illisible' };
  return { ok: true, types };
}

// Chaque cas : arguments, attentes structurelles.
function buildCases(pageTypes) {
  return [
  ...pageTypes.map((pageType) => ({
    name: pageType,
    args: ['--type', pageType, '--title', `Validation ${pageType}`],
    expect: { header: true, footer: true, navigation: true, logo: false, dark: false, title: `Validation ${pageType}` },
  })),
  { name: 'standard--no-header', args: ['--type', 'standard', '--title', 'Validation standard', '--no-header'], expect: { header: false, footer: true, navigation: false, logo: false, dark: false, title: 'Validation standard' } },
  { name: 'standard--no-footer', args: ['--type', 'standard', '--title', 'Validation standard', '--no-footer'], expect: { header: true, footer: false, navigation: true, logo: false, dark: false, title: 'Validation standard' } },
  { name: 'standard--dark', args: ['--type', 'standard', '--title', 'Validation standard', '--dark'], expect: { header: true, footer: true, navigation: true, logo: false, dark: true, title: 'Validation standard' } },
  { name: 'standard--republique', args: ['--type', 'standard', '--title', 'Validation standard', '--brand-mode', 'republique'], expect: { header: true, footer: true, navigation: true, logo: true, dark: false, title: 'Validation standard' } },
  ];
}

function skipOnRuntimeLoadFailure() {
  return process.env.DSFR_INTERACTIVE_SKIP_ON_RUNTIME_LOAD === '1';
}

function generatePages(cases, tmpDir, dsfrPackage, origin) {
  return cases.map((item) => {
    const result = runPython([PAGE_SCRIPT, ...item.args], { cwd: SKILL_DIR });
    if (!result.ok) {
      return { ...item, error: result.error, skip: result.skip };
    }
    const html = patchDsfrCdnToLocal(result.stdout, origin);
    const file = path.join(tmpDir, `${item.name}.html`);
    fs.writeFileSync(file, html, 'utf8');
    return { ...item, file };
  });
}

async function browserFacts(page) {
  await page.keyboard.press('Tab');
  return page.evaluate(() => {
    const idCounts = {};
    for (const node of document.querySelectorAll('[id]')) idCounts[node.id] = (idCounts[node.id] || 0) + 1;
    const ids = new Set(Object.keys(idCounts));
    const missingAria = [];
    const attrs = ['aria-controls', 'aria-labelledby', 'aria-describedby'];
    for (const node of document.querySelectorAll('[aria-controls], [aria-labelledby], [aria-describedby]')) {
      for (const attr of attrs) {
        const value = node.getAttribute(attr);
        if (!value) continue;
        for (const target of value.split(/\s+/).filter(Boolean)) {
          if (!ids.has(target)) missingAria.push(`${attr}=${target}`);
        }
      }
    }
    const headings = Array.from(document.querySelectorAll('h1, h2, h3, h4, h5, h6')).map((node) => Number(node.tagName[1]));
    const headingJumps = headings.filter((level, index) => index > 0 && level > headings[index - 1] + 1).length;

    return {
      lang: document.documentElement.getAttribute('lang'),
      scheme: document.documentElement.getAttribute('data-fr-scheme'),
      title: document.title,
      main: Boolean(document.querySelector('main#contenu')),
      header: Boolean(document.querySelector('header[role="banner"]')),
      footer: Boolean(document.querySelector('footer[role="contentinfo"]#footer')),
      navigation: Boolean(document.querySelector('#navigation')),
      skiplinks: document.querySelectorAll('.fr-skiplinks a[href="#contenu"]').length,
      skiplinkTargetsMissing: Array.from(document.querySelectorAll('.fr-skiplinks a[href^="#"]'))
        .map((node) => node.getAttribute('href').slice(1)).filter((id) => !ids.has(id)),
      h1: document.querySelectorAll('h1').length,
      firstHeading: headings[0] || 0,
      headingJumps,
      duplicateIds: Object.entries(idCounts).filter(([, count]) => count > 1).map(([id]) => id),
      placeholderHref: document.querySelectorAll('a[href="#"]').length,
      missingAria,
      restingConstraints: document.querySelectorAll(
        'input[required], select[required], textarea[required], input[aria-required], select[aria-required], textarea[aria-required], input[pattern], input[aria-invalid], select[aria-invalid], textarea[aria-invalid]'
      ).length,
      frLogo: document.querySelectorAll('.fr-logo').length,
      focusedTag: document.activeElement ? document.activeElement.tagName : '',
      focusedClass: document.activeElement ? document.activeElement.className : '',
    };
  });
}

function issuesFor(item, facts, errors) {
  const issues = [];
  const expect = item.expect;
  if (facts.lang !== 'fr') issues.push('html lang is not fr');
  if (facts.title !== expect.title) issues.push(`unexpected title: ${facts.title}`);
  if (!facts.main) issues.push('main#contenu missing');
  if (facts.header !== expect.header) issues.push(expect.header ? 'header banner missing' : 'header banner present with --no-header');
  if (facts.footer !== expect.footer) issues.push(expect.footer ? 'footer contentinfo missing' : 'footer present with --no-footer');
  if (facts.navigation !== expect.navigation) issues.push(expect.navigation ? 'navigation target missing' : 'navigation present with --no-header');
  if (facts.scheme !== (expect.dark ? 'dark' : 'system')) issues.push(expect.dark ? `data-fr-scheme=dark missing with --dark (${facts.scheme})` : `data-fr-scheme=system expected by default, got ${facts.scheme}`);
  if ((facts.frLogo > 0) !== expect.logo) issues.push(expect.logo ? 'fr-logo missing with --brand-mode republique' : 'default generated page contains fr-logo');
  if (facts.skiplinks < 1) issues.push('skiplink to #contenu missing');
  if (facts.skiplinkTargetsMissing.length > 0) issues.push(`skiplink targets missing: ${facts.skiplinkTargetsMissing.join(', ')}`);
  if (facts.h1 !== 1) issues.push(`expected exactly one h1, found ${facts.h1}`);
  if (facts.firstHeading !== 1) issues.push(`first heading is h${facts.firstHeading}`);
  if (facts.headingJumps > 0) issues.push(`heading level jumps: ${facts.headingJumps}`);
  if (facts.duplicateIds.length > 0) issues.push(`duplicate ids: ${facts.duplicateIds.slice(0, 8).join(', ')}`);
  if (facts.placeholderHref > 0) issues.push('placeholder href found');
  if (facts.missingAria.length > 0) issues.push(`missing aria targets: ${facts.missingAria.slice(0, 8).join(', ')}`);
  if (facts.restingConstraints > 0) issues.push('resting form constraints found');
  if (!FOCUSABLE_TAGS.includes(facts.focusedTag)) issues.push(`first tab did not reach a focusable element (${facts.focusedTag || 'none'})`);
  if (errors.length > 0) issues.push(`console/page errors: ${errors.slice(0, 3).join(' | ')}`);
  return issues;
}

async function main() {
  const { loaded, error: playwrightError } = loadPlaywright();
  if (!loaded) {
    printSkipped(playwrightError || 'Playwright module not found in local node_modules or npx cache.');
    return;
  }
  const { dir: dsfrPackage, version: dsfrVersion, error: dsfrError } = resolveDsfrPackage();
  if (!dsfrPackage) {
    printSkipped(`${dsfrError}. Run check_generated_outputs.py --official-version 1.15.3 to seed the cache.`);
    return;
  }

  const { playwright, version, source } = loaded;
  let tmpDir = null;
  let server = null;
  let browser = null;
  const steps = [
    async () => { if (browser) await browser.close(); },
    async () => { if (server) await server.close(); },
    async () => { if (tmpDir) fs.rmSync(tmpDir, { recursive: true, force: true }); },
  ];
  try {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'dsfr-pages-'));
    server = await startStaticServer([
      { prefix: '/pages/', root: tmpDir },
      { prefix: '/dsfr/', root: path.join(dsfrPackage, 'dist') },
    ]);
    const typesResult = readPageTypes();
    if (!typesResult.ok) {
      if (typesResult.skip) {
        printSkipped(typesResult.error, { playwright: version, source, dsfrPackage, dsfrVersion });
        return;
      }
      console.log(JSON.stringify({ status: 'FAIL', phase: 'generation', errors: [{ name: 'PAGE_TYPES', error: typesResult.error }] }, null, 2));
      process.exitCode = 1;
      return;
    }
    const generated = generatePages(buildCases(typesResult.types), tmpDir, dsfrPackage, server.origin);
    const environmentSkips = generated.filter((item) => item.skip);
    if (environmentSkips.length > 0) {
      printSkipped(environmentSkips[0].error, { playwright: version, source, dsfrPackage, dsfrVersion });
      return;
    }
    const generationErrors = generated.filter((item) => item.error);
    if (generationErrors.length > 0) {
      console.log(JSON.stringify({
        status: 'FAIL',
        phase: 'generation',
        errors: generationErrors.map((item) => ({ name: item.name, error: item.error })),
      }, null, 2));
      process.exitCode = 1;
      return;
    }

    try {
      browser = await playwright.chromium.launch({ headless: true });
    } catch (err) {
      printSkipped(
        'Playwright chromium could not launch. Run `npx playwright install chromium` to enable this check.',
        { playwright: version, source, detail: err.message }
      );
      return;
    }

    const results = [];
    const skipped = [];
    for (const item of generated) {
      const page = await browser.newPage();
      const errors = [];
      page.on('console', (message) => {
        if (message.type() === 'error') errors.push(message.text());
      });
      page.on('pageerror', (err) => errors.push(err.message));
      try {
        await page.goto(`${server.origin}/pages/${path.basename(item.file)}`, { waitUntil: 'domcontentloaded' });
        try {
          await waitForDsfr(page);
        } catch (err) {
          if (skipOnRuntimeLoadFailure()) {
            skipped.push({ name: item.name, reason: 'DSFR runtime could not load before timeout', detail: err.message });
            continue;
          }
          throw err;
        }
        const facts = await browserFacts(page);
        results.push({ name: item.name, issues: issuesFor(item, facts, errors), checks: facts });
      } finally {
        await page.close().catch(() => {});
      }
    }

    const failures = results.filter((result) => result.issues.length > 0);
    // Un échec observé prime sur les pages sautées : il n'est jamais effacé.
    const status = failures.length > 0 ? 'FAIL' : (skipped.length > 0 ? 'SKIPPED' : 'PASS');
    console.log(JSON.stringify({
      status,
      playwright: version,
      source,
      dsfrPackage,
      dsfrVersion,
      pages: results.length,
      skipped,
      failures,
    }, null, 2));
    process.exitCode = status === 'PASS' ? 0 : (status === 'SKIPPED' ? 2 : 1);
  } finally {
    await cleanup(steps);
  }
}

main().catch((err) => {
  // Sortie standard analysable même sur exception ; la pile va sur stderr.
  console.log(JSON.stringify({ status: 'ERROR', reason: err && err.message ? err.message : String(err) }, null, 2));
  console.error(err && err.stack ? err.stack : err);
  process.exitCode = 1;
});
